config/routes.rb
Rails.application.routes.draw do
  match 'auth/facebook/callback', to: 'home#facebook_details', via: [:get, :post]
  match 'auth/instagram/callback', to: 'home#instagram_details', via: [:get, :post]
  match 'auth/pinterest/callback', to: 'home#pinterest_details', via: [:get, :post]
  match 'auth/google/callback', to: 'home#google_details', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match '*path', via: [:options], to:  ->(_) { [200, { 'Content-Type' => 'text/plain' }, []] }

  devise_scope :user do
    post 'users/sessions/login', to: 'users/sessions#login', as: 'user_login'
  end  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  post '/users/confirm_registration' => 'users#confirm_registration'
  get 'get_countries' => 'homes#get_countries'
  get 'get_roles' => 'homes#get_roles'
  get '/users/sessions/failure' => 'users/sessions#failure'
  delete 'sessions' => 'sessions#destroy', :as => 'sign_out'

  get '/user_video/add_video', to: 'user_videos#add_video', as: 'add_video'
  post '/user_video/upload_video', to: 'user_videos#upload_video', as: 'upload_video'
  delete '/user_video/remove_video/:id', to: 'user_videos#remove_video', as: 'remove_video'
  post '/user_video/add_videos', to: 'user_videos#add_videos', as: 'add_videos'
  
  patch '/athletes', to: 'athletes#profile_field_update'
  post '/athletes/public_image', to: 'athletes#update_public_image'
  post '/athletes/cover_image', to: 'athletes#update_cover_image'
  get '/athletes/profile', to: 'athletes#profile'
  get '/athletes/skills', to: 'athletes#skills'
  post '/athletes/skills', to: 'skills#add'
  delete '/athletes/skills', to: 'skills#remove'
  post '/athletes/educations', to: 'educations#create'
  delete '/athletes/educations', to: 'educations#delete'
  put'/athletes/educations', to: 'educations#edit'

  get '/skills', to: 'skills#index'
  get '/skills', to: 'skills#index'
  get '/educations', to: 'educations#index'
  get '/institution', to: 'educations#institution'
  get '/education_type', to: 'educations#education_type'
  post '/charges/creditcard_payment', to: 'charges#creditcard_payment'
  post '/charges/user_stripe_account_id', to: 'charges#user_stripe_account_id'

  get '/payments/upgrade_plans', to: 'payments#upgrade_plans', as: 'upgrade_plans'
  get '/payments/payment_option_page/:id', to: 'payments#payment_option_page', as: 'payment_option_page'
  post '/payments/creditcard_validation',to:'payments#creditcard_validation'
  post '/payments/payment_charge',to:'payments#payment_charge'
  post '/charges/paypal_payment', to: 'charges#paypal_payment'
  post '/payments/stripe_payment', to: 'payments#stripe_payment', as: 'stripe_payment'

  get 'careers/add_career',to: 'careers#add_career' 
  post 'careers/add_career_create',to:'careers#add_career_create',as:'add_careers_create'
  get 'careers/career_edit/:career_id',to: 'careers#career_edit' ,as:'career_edit'
  put 'careers/career_update/:career_id',to: 'careers#career_update',as:'career_update'
  delete 'careers/:career_id', to: 'careers#career_destroy', as: 'career_destroy'

  get 'sponsors/sponsor_new',to: 'sponsors#sponsor_new',as:'sponsors_new'
  post 'sponsors/sponsor_create',to:'sponsors#sponsor_create',as:'sponsor_create'
  get 'sponsors/sponsor_edit/:sponsor_id',to:'sponsors#sponsor_edit',as:'sponsor_edit'
  put 'sponsors/sponsor_update/:sponsor_id',to: 'sponsors#sponsor_update',as:'sponsor_update'
  delete 'sponsors/sponsor_destroy/:sponsor_id',to:'sponsors#sponsor_destroy',as:'sponsor_destroy'

  namespace :admin do
    devise_for :users
    get '/', to: 'dashboard#index'
    resources :users

    namespace :basic do
      resources :countries do
      end
      resources :states do
      end
      resources :cities do
      end
      resources :account_types do
      end
      resources :plans do
      end
      resources :games do
      end
    end
  end
      

  root 'home#index'

  get 'home/index'
  get 'home/view'
  get 'home/edit_profile'
  post 'home/create'
  post 'home/add_education'
  post 'home/add_experiences'
  
  delete 'home/edit_profile', to: 'home#destroy'
  
  patch '/home', to: 'home#update_user_profile'
  put '/home', to: 'home#update_user_profile'
  get '/home/athletes_list'
  get '/home/athlete_campare'
  get '/home/athlete_campare_page'
  get '/home/individual_athlete/:id' => 'home#individual_athlete', as: 'individual_athlete'
  post 'home/profile_update', to: 'home#profile_field_update'
  post '/home/athletes_list', to: 'home#athletes_list', as: 'athletes_list'

get 'albums/album_new', to:'albums#album_new' ,as:'albums_new'
post 'albums/album_create',to:'albums#album_create',as:'albums/album_create'
get 'albums/picture_new',to:'albums#picture_new',as:'picture_new'
post'albums/picture_create',to:'albums#picture_create',as:'albums/picture_create'

end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-below">
    <div class="container">
      <div class="row">
        <div class="col-md-1"> </div>
        <div class="col-md-10" style="text-align:center;">
          <ul class="list-inline footer-list-inline">
            <li>
              <a href="#">Itbeezone© 2016</a>
            </li>
            <li>
              <a href="#">User Agreement</a>
            </li>
            <li>
              <a href="#">Privacy Policy</a>
            </li>
            <li>
              <a href="#" >Community Guidelines</a>
            </li>
            <li>
              <a href="#" >Cookie Policy</a>
            </li>
            <li>
              <a href="#" >Guest Controls</a>
            </li>
            <li>
              <a href="#" >Language</a>
            </li>
          </ul>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-material-blue navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-animations">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">
          <img src="/assets/sports_logo.png" style="width:163px;margin-top: -5px;
          height: 53PX;">
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-animations" data-hover="dropdown" data-animations="fadeInDownNew fadeInRightNew fadeInUpNew fadeInLeftNew">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span><i class="fa fa-newspaper-o"></i></span></a>
            <ul class="dropdown-menu dropdown-menu-new-ver header-drop-down new-head" role="menu">
              <div class="account-setting-title">
                <b>Notification</b>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span><i class="fa fa-flag"></i></span></a>
            <ul class="dropdown-menu dropdown-menu-new-ver header-drop-down new-head" role="menu">
              <div class="account-setting-title">
                <b>Notification</b>
              </div>
              <div class="setting-section new-ac-section">
                <img class="drop-img-new" src="/assets/user1.png">
                <span class="pull-right">1mth</span>
                <span class="new-drop-span">Gopinath murugan</span>
                <span class="new-drop-span-detail">Cricket player at Icc</span>
                <span class="new-drop-span-join"><b>Join AthleteBook</b></span>
              </div>
              <div class="setting-section new-ac-section">
                <img class="drop-img-new" src="/assets/user1.png">
                <span class="pull-right">2mth</span>
                <span class="new-drop-span">Saravanan</span>
                <span class="new-drop-span-detail">Football player at Fcc</span>
                <span class="new-drop-span-join"><b>Join AthleteBook</b></span>
              </div>
              <div class="setting-section new-ac-section">
                <img class="drop-img-new" src="/assets/user1.png">
                <span class="pull-right">3mth</span>
                <span class="new-drop-span">Pradeep</span>
                <span class="new-drop-span-detail">Cricket player at Icc</span>
                <span class="new-drop-span-join"><b>Join AthleteBook</b></span>
              </div>
              <div class="setting-section new-ac-section">
                <img class="drop-img-new" src="/assets/user1.png">
                <span class="pull-right">4mth</span>
                <span class="new-drop-span">Prabhakaran</span>
                <span class="new-drop-span-detail">Football player at Fcc</span>
                <span class="new-drop-span-join"><b>Join AthleteBook</b></span>
              </div>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span><i class="fa fa-user-plus"></i></span></a>
            <ul class="dropdown-menu dropdown-menu-new-ver header-drop-down new-head" role="menu">
              <div class="account-setting-title">
                <b>Notification</b>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
              <div class="setting-section new-ac-section">
                <span><i class="fa fa-briefcase drop-icon"></i></span>
                <span class="pull-right">test link</span>
                <span class="new-drop-span">test name</span>
              </div>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <% if current_user.user_profile.public_image.present? %>
              <img class="drop-img" src="<%=current_user.user_profile.public_image.url%>">
              <% else%>
              <img class="drop-img" src="/assets/user1.png">
              <% end %>
            </a>
            <ul class="dropdown-menu dropdown-menu-new-ver header-drop-down new-head" role="menu">
              <div class="account-setting-title">
                <b>Account & setting</b>
              </div>
              <div class="setting-section">  
                <% if current_user.user_profile.public_image.present? %>
                <img class="drop-img" src="<%=current_user.user_profile.public_image.url%>">
                <% else%>
                <img class="drop-img" src="/assets/user1.png">
                <% end %>
              <span >
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete, :style => 'margin-top: -5px;', :class =>'pull-right date-title') %>
                <% end %>
              <span>
              <span><%= current_user.first_name%></span>
            </div>
            <div class="setting-section">
              <span><i class="fa fa-linkedin-square drop-icon"></i></span>
              <span class="pull-right"><%= link_to "Try Premium", upgrade_plans_path , :class => "premium-link" %></span>
              <span>Account Basic</span>
            </div>
            <div class="setting-section">
              <span><i class="fa fa-briefcase drop-icon"></i></span>
              <span class="pull-right premium-link">Manage</span>
              <span>Job & Posting</span>
            </div>
            <div class="setting-section">
              <span><i class="fa fa-globe drop-icon"></i></span>
              <span class="pull-right premium-link">Changed</span>
              <span>Language</span>
            </div>
            <div class="setting-section">
              <span><i class="fa fa-lock drop-icon"></i></span>
              <span class="pull-right premium-link">Manage</span>
              <span>Privacy & Settings</span>
            </div>
            <div class="setting-section">
              <span><i class="fa fa-question-circle drop-icon"></i></span>
              <span class="pull-right premium-link">Get Help</span>
              <span>Help Center</span>
            </div>
          </ul>
        </li>
      </ul>
      <div class="row">
        <div class="col-xs-12 col-md-4 col-sm-4 search-filter">
          <div class="input-group">
            <div class="input-group-btn search-panel dropdown">
              <button type="button" class="btn btn-default dropdown-toggle filter-btn iconButton" data-toggle="dropdown">
                <% if @role_id != nil %>
                  <span id="search_concept"><i class="<%= @role_id %>" aria-hidden="true"></i></span> <span class="caret"></span>
                <% else %>
                  <span id="search_concept"><i class="fa fa-bars" aria-hidden="true"></i></span> <span class="caret"></span>
                <% end %>
              </button>
              <ul class="dropdown-menu filter-dropdown-menu search-dropdown-menu" role="menu">
                <li class="searchValue" data-roleid="0"><i class="fa fa-search faIcon" aria-hidden="true" ></i> All</li>
                <li class="searchValue" data-roleid="1"><i class="fa fa-user faIcon" aria-hidden="true" ></i> Athlete</li>
                <li class="searchValue" data-roleid="2"><i class="fa fa-users faIcon" aria-hidden="true" ></i> Team</li>
                <li class="searchValue" data-roleid="3"><i class="fa fa-building-o faIcon" aria-hidden="true" ></i> Company</li>
              </ul>
            </div>
            <%= search_form_for @q, url: athletes_list_path, html: {id: "ransackSearchForm", method: :post } do |f| %>
              <%= f.search_field :first_name_or_last_name_or_email_cont, id: "searchField", class: "search form-control", type: "text",placeholder: "search for people,Comapnies,and more...", style:"width:84%;height: 30px;"%>
              <%= f.submit class:"btn search-btn", id: "ransackSearch"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_register.html.erb
<%= form_for :user, url: home_create_path, :html => {id: "newRegistration"}, remote: true, method: :post do |f| %>
  <%= devise_error_messages! %>
  <fieldset>
    <div style="text-align: center;margin-top: 30px;">
      <p style="font-size: 15px;">Get started - it's free.</p>
      <div class="error-msg">
        <% if flash[:error] %>
          <% flash[:error].each do |error| %>
            <li>
              <%= error %>
            </li>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-12 control-label">Account Type</label>
      <div class="col-lg-12">
        <%=f.select :role_id, Role.where.not(name: 'admin').collect{|r| [r.name, r.id] } ,{},class: "form-control select-option login-type",name:"user[role_id]" %>
      </div>
    </div>

    <div class="athelet-form">
      <div class="form-group">
        <label class="col-lg-12 control-label">First name</label>
        <div class="col-lg-12">
          <%= f.text_field :first_name, :class => 'form-control',name:"user[first_name]"%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-lg-12 control-label">Last name</label>
        <div class="col-lg-12">
          <%= f.text_field :last_name, :class => 'form-control',name:"user[last_name]" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-lg-12 control-label">Email</label>
        <div class="col-lg-12">
          <%= f.text_field :email, :class => 'form-control',name:"user[email]" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-lg-12 control-label">Password (6 or more characters)</label>
        <div class="col-lg-12">
          <%= f.password_field :password, :class => 'form-control',name:"user[password]"%>
        </div>
      </div>
      <div class="control-group">
        <div class="col-md-12">
          <p class="disclosure-text">By clicking Join now, you agree to Itbeezone's <b>User Agreement,
          Privacy Policy</b>, and <b>Cookie Policy</b>.</p>
        </div>
      </div>

      <div class="control-group">
         <div class="col-md-12">    
            <%= f.submit 'Sign up', :class => 'join-btn large-them-btn'%>
         </div>
      </div>
    </div>

    <div class="team-form">
      <div class="form-group">
        <label class="col-lg-12 control-label">Team name</label>
        <div class="col-lg-12">
         <%= f.text_field :first_name, :class => 'form-control',name:"user[first_name]" %>
          <!-- <input type="text" id="teaname" name="teamname"  class="form-control input-lg" placeholder =  "TeamName"> -->
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-12 control-label">Email</label>
        <div class="col-lg-12">
          <%= f.text_field :email, :class => 'form-control',name:"user[email]" %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-12 control-label">Password (6 or more characters)</label>
        <div class="col-lg-12">
          <%= f.password_field :password, :class => 'form-control',name:"user[password]"%>
        </div>
      </div>
      <div class="control-group">
        <div class="col-md-12">
          <p class="disclosure-text">By clicking Join now, you agree to Itbeezone's <b>User Agreement,
          Privacy Policy</b>, and <b>Cookie Policy</b>.</p>
        </div>
      </div>

      <div class="control-group">
        <div class="col-md-12">
          <%= f.submit 'Sign up', :class => 'join-btn large-them-btn'%>
        </div>
      </div>
    </div>
    <div class="company-form">
      <div class="form-group">
        <label class="col-lg-12 control-label">Company name</label>
        <div class="col-lg-12">
          <%= f.text_field :company_name, :class => 'form-control',name:"user[company_name]" %>
        </div>
      </div>
      
      <div class="form-group">
        <label class=" control-label col-lg-12">Company logo</label>
        <div class="col-lg-12">
          <%= f.file_field :company_logo, :class => 'custom-file-input' %>
        </div>
      </div>


      <div class="form-group">
        <label class="col-lg-12 control-label">Email</label>
        <div class="col-lg-12">
          <%= f.text_field :email, :class => 'form-control',name:"user[email]" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-lg-12 control-label">Password (6 or more characters)</label>
        <div class="col-lg-12">
          <%= f.password_field :password, :class => 'form-control',name:"user[password]"%>
        </div>
      </div>
      <div class="control-group">
        <div class="col-md-12">
          <p class="disclosure-text">By clicking Join now, you agree to Itbeezone's <b>User Agreement,
          Privacy Policy</b>, and <b>Cookie Policy</b>.</p>
        </div>
      </div>
     <div class="control-group">
        <div class="col-md-12">
          <%= f.submit 'Sign up', :class => 'join-btn large-them-btn'%>
        </div>
     </div>
    </div>
  </fieldset>
<% end %>

app/views/shared/_sub_header.html.erb
<nav-sub> 
  <a id="resp-menu" class="responsive-menu" href="#"><i class="fa fa-reorder"></i> Menu</a>
  <ul class="menu menu-align">
    <li><a href="#">Home</a>
    <li><a href="#">Profile</a>
      <ul class="sub-menu">
        <li><a href="#">Edit profile</a></li>
        <li><a href="#">Who's viewed profile</a></li>
        <li><a href="#">Your Updates</a></li>

      </ul>
    </li>
    <li><a  href="#"></i> My Network</a>
      <ul class="sub-menu">
        <li><a href="#">Conection</a></li>
        <li><a href="#">Add contacts</a></li>
        <li><a href="#">People you may Know</a></li>
        <li><a href="#">Find alumni</a></li>
      </ul>
    </li>
    <li><a  href="#"> Athlete List</a></li>
    <li><a  href="#">Recent Activity</a>
      <ul class="sub-menu">
        <li><a href="#">Talent solutios</a></li>
        <li><a href="#">Advertise</a></li>
      </ul>
    </li>
    <li><a  href="#"><%= current_user.user_plan.try(:plan).try(:name) ? current_user.user_plan.try(:plan).try(:name) : "Try Premium" %></a>
      <ul class="sub-menu">
        <% @plans.each do |p| %>
          <li><%= link_to p.name, payment_option_page_path(p) %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</nav-sub>