config/routes.rb
Rails.application.routes.draw do
  match 'auth/facebook/callback', to: 'home#facebook_details', via: [:get, :post]
  match 'auth/instagram/callback', to: 'home#instagram_details', via: [:get, :post]
  match 'auth/pinterest/callback', to: 'home#pinterest_details', via: [:get, :post]
  match 'auth/google/callback', to: 'home#google_details', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match '*path', via: [:options], to:  ->(_) { [200, { 'Content-Type' => 'text/plain' }, []] }

  devise_scope :user do
    post 'users/sessions/login', to: 'users/sessions#login', as: 'user_login'
  end  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  post '/users/confirm_registration' => 'users#confirm_registration'
  get 'get_countries' => 'homes#get_countries'
  get 'get_roles' => 'homes#get_roles'
  get '/users/sessions/failure' => 'users/sessions#failure'
  delete 'sessions' => 'sessions#destroy', :as => 'sign_out'

  get '/user_video/add_video', to: 'user_videos#add_video', as: 'add_video'
  post '/user_video/upload_video', to: 'user_videos#upload_video', as: 'upload_video'
  delete '/user_video/remove_video/:id', to: 'user_videos#remove_video', as: 'remove_video'
  post '/user_video/add_videos', to: 'user_videos#add_videos', as: 'add_videos'
  
  patch '/athletes', to: 'athletes#profile_field_update'
  post '/athletes/public_image', to: 'athletes#update_public_image'
  post '/athletes/cover_image', to: 'athletes#update_cover_image'
  get '/athletes/profile', to: 'athletes#profile'
  get '/athletes/skills', to: 'athletes#skills'
  post '/athletes/skills', to: 'skills#add'
  delete '/athletes/skills', to: 'skills#remove'
  post '/athletes/educations', to: 'educations#create'
  delete '/athletes/educations', to: 'educations#delete'
  put'/athletes/educations', to: 'educations#edit'

  get '/skills', to: 'skills#index'
  get '/skills', to: 'skills#index'
  get '/educations', to: 'educations#index'
  get '/institution', to: 'educations#institution'
  get '/education_type', to: 'educations#education_type'
  post '/charges/creditcard_payment', to: 'charges#creditcard_payment'
  post '/charges/user_stripe_account_id', to: 'charges#user_stripe_account_id'

  get '/payments/upgrade_plans', to: 'payments#upgrade_plans', as: 'upgrade_plans'
  get '/payments/payment_option_page/:id', to: 'payments#payment_option_page', as: 'payment_option_page'
  post '/payments/creditcard_validation',to:'payments#creditcard_validation'
  post '/payments/payment_charge',to:'payments#payment_charge'
  post '/charges/paypal_payment', to: 'charges#paypal_payment'
  post '/payments/stripe_payment', to: 'payments#stripe_payment', as: 'stripe_payment'

  get 'careers/add_career',to: 'careers#add_career' 
  post 'careers/add_career_create',to:'careers#add_career_create',as:'add_careers_create'
  get 'careers/career_edit/:career_id',to: 'careers#career_edit' ,as:'career_edit'
  put 'careers/career_update/:career_id',to: 'careers#career_update',as:'career_update'
  delete 'careers/:career_id', to: 'careers#career_destroy', as: 'career_destroy'

  get 'sponsors/sponsor_new',to: 'sponsors#sponsor_new',as:'sponsors_new'
  post 'sponsors/sponsor_create',to:'sponsors#sponsor_create',as:'sponsor_create'
  get 'sponsors/sponsor_edit/:sponsor_id',to:'sponsors#sponsor_edit',as:'sponsor_edit'
  put 'sponsors/sponsor_update/:sponsor_id',to: 'sponsors#sponsor_update',as:'sponsor_update'
  delete 'sponsors/sponsor_destroy/:sponsor_id',to:'sponsors#sponsor_destroy',as:'sponsor_destroy'

  namespace :admin do
    devise_for :users
    get '/', to: 'dashboard#index'
    resources :users

    namespace :basic do
      resources :countries do
      end
      resources :states do
      end
      resources :cities do
      end
      resources :account_types do
      end
      resources :plans do
      end
      resources :games do
      end
    end
  end
      

  root 'home#index'

  get 'home/index'
  get 'home/view'
  get 'home/edit_profile'
  post 'home/create'
  post 'home/add_education'
  post 'home/add_experiences'
  
  delete 'home/edit_profile', to: 'home#destroy'
  
  patch '/home', to: 'home#update_user_profile'
  put '/home', to: 'home#update_user_profile'
  get '/home/athletes_list'
  get '/home/athlete_campare'
  get '/home/athlete_campare_page'
  get '/home/individual_athlete/:id' => 'home#individual_athlete', as: 'individual_athlete'
  post 'home/profile_update', to: 'home#profile_field_update'
  post '/home/athletes_list', to: 'home#athletes_list', as: 'athletes_list'

get 'albums/album_new', to:'albums#album_new' ,as:'albums_new'
post 'albums/album_create',to:'albums#album_create',as:'albums/album_create'
get 'albums/picture_new',to:'albums#picture_new',as:'picture_new'
post'albums/picture_create',to:'albums#picture_create',as:'albums/picture_create'

end

app/controllers/api/v1/homes_controller.rb
class HomesController < ApplicationController

  def get_countries
    @countries = Country.all
    render :status => 200,
           :json => { :success => true,
                      :countries => @countries }
  end

  def get_roles
  	@roles = Role.where.not(name: 'admin')
  	render :status => 200,
           :json => { :success => true,
                      :roles => @roles }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include JsonRenderHelper
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :authenticate_user!, except: [:index, :create]
  def index
    #redirect_to admin_path if current_admin_user.present?
    redirect_to home_view_path if current_user
    @q = User.ransack(params[:q])
    @search = @q.result(distinct: true)

  end

  # social power
  def facebook_details
    access_token = env["omniauth.auth"]['credentials']['token']
    @graph = Koala::Facebook::API.new(access_token)
    @profile = @graph.get_object("me")
    @likes = @graph.get_connections("me", "likes").count
    @friends = @graph.get_connections("me", "friends").count
    @invitable_friends = @graph.get_connections("me", "invitable_friends").count
    @permission_check = @graph.get_connections('me','permissions')
    p @graph
    p 'user_details'
    p @profile
    p 'friends'
    p @friends
    p 'invitable_friends'
    p @invitable_friends
    p 'likes'
    p @likes  
    redirect_to home_edit_profile_path
  end

  def instagram_details
    access_token = env["omniauth.auth"]['credentials']['token']
    p 'access_token_instagram'
    p access_token
    session[:access_token] = access_token
    Instagram.configure do |config|
      config.client_id = "49873a0d67bd43b48b137e4fff7e15ef"
      config.client_secret = "284792c411774d9f8a52042cc1804e27"
    end
    client = Instagram.client(:access_token => session[:access_token])
    user = client.user
    username = user.username
    full_name = user.full_name
    counts = user.counts
    followed_by = counts.followed_by
    follows = counts.follows
    p 'user details'
    p user = client.user
    p 'username'
    p username
    p 'follows'
    p follows
    p 'followed_by'
    p followed_by
    redirect_to home_edit_profile_path
  end

  def pinterest_details
    p 'pinterest_details'
    redirect_to home_edit_profile_path
  end

  def google_details
    p 'google_details'
    redirect_to home_edit_profile_path
  end
  # social power end


  def athletes_list
    if params[:q]
      role_icons = {"0"=> "fa fa-search", "1"=> "fa fa-user", "2"=> "fa fa-users", "3"=> "fa fa-building-o"}
      @role_id = role_icons[params[:q][:role_id]]
      if params[:q][:role_id].to_i != 0
        @search_string = params[:q][:first_name_or_last_name_or_email_cont] 
        @q = User.ransack(first_name_or_last_name_or_email_cont: @search_string, role_id_eq: params[:q][:role_id])
        @search = @q.result(distinct: true)
        
      else
        @search_string = params[:q][:first_name_or_last_name_or_email_cont] 
        @q = User.ransack(first_name_or_last_name_or_email_cont: @search_string)
        @search = @q.result(distinct: true)
      end
    else
      redirect_to root_path
    end
  end

  def athlete_campare
    session[:athlete_id] = [] unless session[:athlete_id]
    if session[:athlete_id].length < 4 
      session[:athlete_id] << params[:user]
    else
      flash[:error] = 'You have already selected 4 Athletes'
    end
    redirect_to home_athletes_list_path
  end

  def athlete_campare_page
    @athlete = []
    if session[:athlete_id] == nil
      @message = "not found"
    else
      session[:athlete_id].each do |user_id|
        user_id
        @user = User.find_by_id(user_id)
        @athlete << @user.user_profile
      end
      session[:athlete_id] = nil
    end
    
  end

  def individual_athlete
    @user = User.find_by_id(params[:id])
    @athlete = @user.user_profile
  end

  def view
    @plans = Plan.all
    @career_all =  current_user.careers
    @uservideos = current_user.user_videos.all
    @sponsors = current_user.sponsors
  end

  def profile_field_update
    @edit_profile = current_user.user_profile   
    @edit_profile.update(cover_image: params[:cover_image], public_image: params[:public_image], description: params[:description])
      redirect_to home_edit_profile_path
  end   

  def edit_profile
    @uservideos = current_user.user_videos.all
    @educations_all = current_user.educations
    @career_all = current_user.careers
    @experiences_all = current_user.experiences
    @skill_all  = Skill.all
    @athlete_skills = current_user.skills
    @user = User.all
    @sponsors = current_user.sponsors
  end

  def create
    @user = User.create(user_params)
  end

  def destroy
    skill = Skill.where(id: params[:id].to_i).first
    @athlete_skills = current_user.skills.where(id: skill.id).first
    if skill.present? && @athlete_skills.present?
      @athlete_skills.delete
      redirect_to home_edit_profile_path
    else
      redirect_to home_edit_profile_path
    end
  end

  def build_resource(hash=nil)
    self.resource = resource_class.new_with_session(hash || {}, session)
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def resource_class
    devise_mapping.to
  end

  def active_for_authentication?
    true
  end

  def set_flash_message!(key, kind, options = {})
    if is_flashing_format?
      set_flash_message(key, kind, options)
    end
  end

  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :role_id, :account_type_id, :gender, :date_of_birth, :country_id, :team_name, :plan_id, :company_name, :company_logo)
  end

  def education_params
    params.require(:education).permit(:id, :period, :course_of_study, :activities, :descripition, :user_id, :institution_id, :education_type_id)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def get_countries
    @countries = Country.all
    render :status => 200,
           :json => { :success => true,
                      :countries => @countries }
  end

  def get_roles
  	@roles = Role.where.not(name: 'admin')
  	render :status => 200,
           :json => { :success => true,
                      :roles => @roles }
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def user_details(user, name)
		case name
		when 'first_name'
			user.first_name ? user.first_name : 'First name empty'
		when 'last_name'
			user.last_name ? user.last_name : 'Last name empty'
		when 'gender'
			user.gender ? user.gender : 'Gender empty'
		when 'email'
			user.email ? user.email : 'Email empty'
		when 'date_of_birth'
			user.date_of_birth ? user.date_of_birth : 'Date Of Birth empty'
		end
	end

	def athlete_details(athlete, name)
		case name
		when 'public_image'
				athlete.public_image ? athlete.public_image : 'public_image empty'
		when 'phone'
			athlete.phone ? athlete.phone : 'phone empty'
		when 'sports_name'
			athlete.sports_name ? athlete.sports_name : 'sports_name empty'
		when 'address'
			athlete.address ? athlete.address : 'address empty'
		when 'college'
			athlete.college ? athlete.college : 'college empty'
		when 'exp'
			athlete.exp ? athlete.exp : 'exp empty'
		when 'description'
			athlete.description ? athlete.description : 'description empty'
		end
	end
end

app/views/home/athlete_campare_page.html.erb
<div class="bs-demo-showcase">
  <nav class="navbar navbar-material-blue navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-animations">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">
          <img src="/assets/sports_logo.png" style="width:163px;margin-top: -5px;
          height: 53PX;">
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-animations" data-hover="dropdown" data-animations="fadeInDownNew fadeInRightNew fadeInUpNew fadeInLeftNew">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span><i class="fa fa-newspaper-o"></i></span></a>
            <ul class="dropdown-menu header-drop-down" role="menu">
              <li><a href="#">Account & setting</a></li>
              <li><a href="#">Another action</a></li>
              
              <li class="dropdown">
                <a href="#">Another dropdown 2 <span class="caret"></span></a>
              </li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span><i class="fa fa-bell-o"></i></span></a>
            <ul class="dropdown-menu header-drop-down" role="menu">
              <li><a href="#">Account & setting</a></li>
              <li><a href="#">Another action</a></li>
              
              <li class="dropdown">
                <a href="#">Another dropdown 2 <span class="caret"></span></a>
              </li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span><i class="fa fa-user-plus"></i></span></a>
            <ul class="dropdown-menu header-drop-down" role="menu">
              <li><a href="#">Account & setting</a></li>
              <li><a href="#">Another action</a></li>
              
              <li class="dropdown">
                <a href="#">Another dropdown 2 <span class="caret"></span></a>
              </li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="caret"></span></a>
            <ul class="dropdown-menu header-drop-down" role="menu">
              <div class="account-setting-title">
                Account & setting
              </div>
              <div class="setting-section">  
                <span >
                  <% if user_signed_in? %>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete, :style => 'margin-right: 9px;margin-top: -5px;', :class =>'pull-right date-title') %>
                  <% end %>
                <span>
                <span style="margin-left:5px;"><%= current_user.first_name%></span>
              </div>
              <div class="setting-section">
                <span class="pull-right">Try Premium</span>
                <span>Account Basic</span>
              </div>
              <div class="setting-section">
                <span class="pull-right">Manage</span>
                <span>Privacy & Settings</span>
              </div>
              <div class="setting-section">
                <span class="pull-right">Changed</span>
                <span>Language</span>
              </div>
              <div class="setting-section">
                <span class="pull-right">Get Help</span>
                <span>Help Center</span>
              </div>
            </ul>
          </li>
        </ul>
        <div class="row">    
          <div class="col-xs-12 col-md-4 col-sm-4 search-filter" style="width:50%;margin-left:10%; margin-top:20px;">
            <div class="input-group">
              <div class="input-group-btn search-panel dropdown">
                <button type="button" class="btn btn-default dropdown-toggle filter-btn" data-toggle="dropdown" style="border-radius:0px;background: #575757;background-image: -webkit-linear-gradient(top, #888888 0%,#888888 4%,#575757 100%); border:1px solid #888888;">
                  <span id="search_concept"><i class="fa fa-bars" aria-hidden="true"></i></span> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu filter-dropdown-menu" role="menu">
                  <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i>All</a></li>
                  <li><a href="#">People</a></li>
                  <li><a href="#"><i class="fa fa-building-o" aria-hidden="true"></i>Company</a></li>
                  <li><a href="#">Team</a></li>
                </ul>
              </div>
              <input type="hidden" name="search_param" value="all" id="search_param">         
              <input class="search form-control" type="text"  placeholder="search for people,Comapnies,and more...">
              <span class="input-group-btn">
                <button class="btn search-btn" type="button" style="margin-left:3px;">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </span>
            </div>
          </div>
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>
<!-- nav -->


<!-- new sub head -->
<div class="sub-head">
  <nav id="main-nav" role="navigation">
    <ul id="main-menu" class="sm sm-blue">
      <li><a href="">Home</a></li>
      <li><a href="#/edit_profile"> Profile </a>
        <ul class="new-ul">
          <li><a href="#/edit_profile">Edit Profile</a></li>
          <li><a href="">Who's Viewed Your Profile</a></li>
          <li><a href="">Your Updates</a>
        </ul>
      </li>
      <li><a href="">My Network</a>
        <ul class="new-ul">
          <li><a href="">Conection</a></li>
          <li><a href="">Add Contacts</a></li>
          <li><a href="">People You Mayknow</a>
          <li><a href="">Find Alumni</a>
        </ul>
      </li>
      <li><a href="">Jobs</a></li>
      <li><a href="">Interests</a>
        <ul class="new-ul">
          <li><a href="">Companies</a></li>
          <li><a href="">Groups</a></li>
          <li><a href="">SlidShare</a></li>
          <li><a href="">Learning</a>
        </ul>
      </li>
      <li><a href="">Business Services</a>
        <ul class="new-ul">
          <li><a href="">Post a Job</a></li>
          <li><a href="">Talent solutions</a></li>
          <li><a href="">Advertise</a></li>
          <li><a href="">Sales Solutions</a>
        </ul>
      </li>
      <li><a href="">Try Premium</a>
        <ul class="new-ul">
          <li><a href="">Post a Jop</a></li>
          <li><a href="">Talent solutions</a></li>
          <li><a href="">Advertise</a></li>
          <li><a href="">Sales Solutions</a>
          </ul>
      </li>
    </ul>
  </nav>
</div>

<h3 align="center">Campare Athlete</h3>


<% if @message.present? %>
	<h2 align="center"><%= @message %></h2>
<% else %>
  <div class="col-1-5 hero-feature">
    <div class="thumbnail">
      <img src="/assets/800x500.png" alt="">
      <div class="caption">
        <%#= image_tag athlete.public_image.url %>
        <p class="text-bold">Public Image :</p>
        <p class="text-bold">Sports Name :</p>
        <p class="text-bold">Address :</p>
        <p class="text-bold">College :</p>
        <p class="text-bold">Exp :</p>
        <p class="text-bold">Description :</p>
      </div>
    </div>
  </div>
  <% @athlete.each do |athlete|%>
  <div class="col-1-5 hero-feature">
    <div class="thumbnail">
      <img src="/assets/800x500.png" alt="">
      <div class="caption">
       <%#= image_tag athlete.public_image.url %>
        <p><%= athlete.public_image.present? ? athlete.public_image : "Public Image Empty" %></p>
        <p><%= athlete.sports_name.present? ? athlete.sports_name : "Sports Name Empty" %></p>
        <p><%= athlete.address.present? ? athlete.address : "Address Empty"%></p>
        <p><%= athlete.college.present? ? athlete.college : "College Empty"%></p>
        <p><%= athlete.exp.present? ? athlete.exp : "Exp Empty"%></p>
        <p><%= athlete.description.present? ? athlete.description : "Description Empty"%></p>
      </div>
    </div>
  </div>
  <% end %>
<% end %>
	

app/views/home/athletes_list.html.erb
<h3 align="center">Search "<%= @search_string.present? ? @search_string : "users" %>"</h3>
<p style="color:red;"><%= flash[:error] %></p>
<div class="campare-btn">
  <% @sess_val = session[:athlete_id] ? session[:athlete_id].uniq : 0 %>
  <% if session[:athlete_id] && @sess_val.length > 1 %>
  <%= link_to 'Compare multiple', home_athlete_campare_page_path(session[:athlete_id]), :class => 'btn btn-success'%>
  <span class="badge"><%= @sess_val.length %></span>
  <% end %>
</div>
<!-- Page Features -->
<div class="container">
	<div class="row text-center">
		<% @search.each do |user|%>
		<%= link_to individual_athlete_path(user) do %>
			<div class="col-md-3 col-sm-6 hero-feature">
				<div class="thumbnail">
					<img src="/assets/800x500.png" alt="">
					<div class="caption">
						<h3><%= user.first_name %></h3>
						<p><%=h truncate(user.user_profile.try(:description) ? user.user_profile.try(:description) : 'Description Empty' , :length => 20 )  %></p>
						<p>
							<%#= link_to 'View Now!', individual_athlete_path(athlete), :class => 'btn btn-primary' %> <%= link_to 'More Info', individual_athlete_path(user), :class => 'btn btn-default' %>
						</p>
					</div>
				</div>
			</div>
		<% end %>
		<% end%>
    <% else %>
	</div>
</div>	

app/views/home/create.js.erb
<% if @user.persisted? %>
	$(".notice").html("Confirmation mail was sent your email. Please check your email.");
	$("#newRegistration").trigger("reset");
	clearImageName();
<% else %>
	$(".notice").html("Can't create your account. Please try again.");
	$("#newRegistration").trigger("reset");
	clearImageName();
<% end %>

app/views/home/index.html.erb
<body id="page-top" class="index">
  <div class="bs-demo-showcase">
    <nav class="navbar nav-login-header navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-animations">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand ab-nav">
            <img src="/assets/sports_logo.png" style="width:75px";>
          </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-animations" data-hover="dropdown" data-animations="fadeInDownNew fadeInRightNew fadeInUpNew fadeInLeftNew">
          <div class="row new-nav-bg">    
            <div class="col-xs-12 col-md-12 col-sm-12 search-filter-regis" style="text-align:right">
              <%= form_for(:user, url: session_path(:user), :html => {id: "loginPage"}) do |f| %>
<!-- old code -->
                <!-- <span> 
                  <%#= f.email_field :email, :placeholder => 'Email', :class => "new-ab-login-ins", :style => 'width: 235px;height: 30px;margin-right: 10px; text-indent:12px;font-size:12px;margin-bottom:3px;color:#000;border:1px solid #696969;border-radius:3px', 'data-fv' => 'true', 'data-fv_type' => 'email', 'data-fv_err_msg' => 'Invalid Email Id'%>
                </span>
                <span>
                  <%#= f.password_field :password, autocomplete: "off", :placeholder => 'Password', :class => "new-ab-login-ins", :style => 'width: 235px;height: 30px;margin-right: 10px;text-indent:12px;font-size:12px;margin-bottom:3px;color:#000;border:1px solid #696969;border-radius: 3px;' %>
                </span>
                <span>
                  <%#= f.submit "Log in", :style => 'height: 28px; border: 1px;color:#000;width:60px;border-radius: 3px;background-image: -webkit-linear-gradient(top, #f2f2f2 0%,#e9e9e9 32%,#d8d8d8 74%,#d1d1d1 100%);box-sizing: border-box;font-size: 12px;color: #444;background-color: #f2f2f2;border-color: #a7a7a7;'%>
                  <button id="loginButton", type="button" , style = 'height: 28px; border: 1px;color:#000;width:60px;border-radius: 3px;background-image: -webkit-linear-gradient(top, #f2f2f2 0%,#e9e9e9 32%,#d8d8d8 74%,#d1d1d1 100%);box-sizing: border-box;font-size: 12px;color: #444;background-color: #f2f2f2;border-color: #a7a7a7;'>Log in</button>
                </span>
             <%#end%>
             <span style="margin-right:24%;">
                <%#= link_to "Forgot your password?", new_password_path(:user), style: "font-size:12px;", :class => "new-ab-forget-link"%> -->
<!-- old code -->
              <div class="ab-login-box">
                <div class="form-group">
                  <div class="col-lg-4">
                    <%= f.email_field :email, :placeholder => 'Email', name:'email',:class => 'ab-email-ins'%>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-4">
                    <%= f.password_field :password, autocomplete: "off", :placeholder => 'Password', name:'password',:class => 'ab-password-ins'%>
                  </div>
                </div>
              </div>
              <%= f.submit'Log in',:class => 'ab-btn '%>
             <%end%>
             <span style="margin-right:24%;">
                <%= link_to "Forgot your password?", new_password_path(:user),:class =>'ab-forget-btn'%>
             </span><span class="message" style="text-align:pull-right; color: red;"><%= flash[:message] %></span>
            </div>
          </div>
        </div>
        <div>
            <div class="notice" style="text-align:center; color: white;"><%= flash[:notice] %></div>
        </div>
      </div>
    </nav>
  </div>
  <div id="contact">
    <div class="container">
      <div class="row">
        <div class="col-md-12 md-12">
          <div class="col-md-6 col-md-offset-3 md-6">
            <%= render 'shared/register'%>
          </div> 
        </div>
      </div>
    </div>
  </div>
  <footer>
    <div class="footer-above">
      <div class="container">
        <div class="row">
          <div class=" col-md-2"></div>
            <div class="col-md-8" style="text-align:center">
              <label class="control-label" style="margin-right: 10px;font-size:13px;">Find a colleague:</label>
              <input type="text" name="firstname" placeholder=" First Name" class="ab-email-ins">
              <input type="text" name="secondname" placeholder="Last Name" class="ab-password-ins">
              <button class="ab-btn">search</button>
            </div>
            <div class="col-md-2"></div>
          </div>
        </div>
      </div>
    </div>
  </footer>    
</body>