config/routes.rb
Rails.application.routes.draw do
  match 'auth/facebook/callback', to: 'home#facebook_details', via: [:get, :post]
  match 'auth/instagram/callback', to: 'home#instagram_details', via: [:get, :post]
  match 'auth/pinterest/callback', to: 'home#pinterest_details', via: [:get, :post]
  match 'auth/google/callback', to: 'home#google_details', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match '*path', via: [:options], to:  ->(_) { [200, { 'Content-Type' => 'text/plain' }, []] }

  devise_scope :user do
    post 'users/sessions/login', to: 'users/sessions#login', as: 'user_login'
  end  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  post '/users/confirm_registration' => 'users#confirm_registration'
  get 'get_countries' => 'homes#get_countries'
  get 'get_roles' => 'homes#get_roles'
  get '/users/sessions/failure' => 'users/sessions#failure'
  delete 'sessions' => 'sessions#destroy', :as => 'sign_out'

  get '/user_video/add_video', to: 'user_videos#add_video', as: 'add_video'
  post '/user_video/upload_video', to: 'user_videos#upload_video', as: 'upload_video'
  delete '/user_video/remove_video/:id', to: 'user_videos#remove_video', as: 'remove_video'
  post '/user_video/add_videos', to: 'user_videos#add_videos', as: 'add_videos'
  
  patch '/athletes', to: 'athletes#profile_field_update'
  post '/athletes/public_image', to: 'athletes#update_public_image'
  post '/athletes/cover_image', to: 'athletes#update_cover_image'
  get '/athletes/profile', to: 'athletes#profile'
  get '/athletes/skills', to: 'athletes#skills'
  post '/athletes/skills', to: 'skills#add'
  delete '/athletes/skills', to: 'skills#remove'
  post '/athletes/educations', to: 'educations#create'
  delete '/athletes/educations', to: 'educations#delete'
  put'/athletes/educations', to: 'educations#edit'

  get '/skills', to: 'skills#index'
  get '/skills', to: 'skills#index'
  get '/educations', to: 'educations#index'
  get '/institution', to: 'educations#institution'
  get '/education_type', to: 'educations#education_type'
  post '/charges/creditcard_payment', to: 'charges#creditcard_payment'
  post '/charges/user_stripe_account_id', to: 'charges#user_stripe_account_id'

  get '/payments/upgrade_plans', to: 'payments#upgrade_plans', as: 'upgrade_plans'
  get '/payments/payment_option_page/:id', to: 'payments#payment_option_page', as: 'payment_option_page'
  post '/payments/creditcard_validation',to:'payments#creditcard_validation'
  post '/payments/payment_charge',to:'payments#payment_charge'
  post '/charges/paypal_payment', to: 'charges#paypal_payment'
  post '/payments/stripe_payment', to: 'payments#stripe_payment', as: 'stripe_payment'

  get 'careers/add_career',to: 'careers#add_career' 
  post 'careers/add_career_create',to:'careers#add_career_create',as:'add_careers_create'
  get 'careers/career_edit/:career_id',to: 'careers#career_edit' ,as:'career_edit'
  put 'careers/career_update/:career_id',to: 'careers#career_update',as:'career_update'
  delete 'careers/:career_id', to: 'careers#career_destroy', as: 'career_destroy'

  get 'sponsors/sponsor_new',to: 'sponsors#sponsor_new',as:'sponsors_new'
  post 'sponsors/sponsor_create',to:'sponsors#sponsor_create',as:'sponsor_create'
  get 'sponsors/sponsor_edit/:sponsor_id',to:'sponsors#sponsor_edit',as:'sponsor_edit'
  put 'sponsors/sponsor_update/:sponsor_id',to: 'sponsors#sponsor_update',as:'sponsor_update'
  delete 'sponsors/sponsor_destroy/:sponsor_id',to:'sponsors#sponsor_destroy',as:'sponsor_destroy'

  namespace :admin do
    devise_for :users
    get '/', to: 'dashboard#index'
    resources :users

    namespace :basic do
      resources :countries do
      end
      resources :states do
      end
      resources :cities do
      end
      resources :account_types do
      end
      resources :plans do
      end
      resources :games do
      end
    end
  end
      

  root 'home#index'

  get 'home/index'
  get 'home/view'
  get 'home/edit_profile'
  post 'home/create'
  post 'home/add_education'
  post 'home/add_experiences'
  
  delete 'home/edit_profile', to: 'home#destroy'
  
  patch '/home', to: 'home#update_user_profile'
  put '/home', to: 'home#update_user_profile'
  get '/home/athletes_list'
  get '/home/athlete_campare'
  get '/home/athlete_campare_page'
  get '/home/individual_athlete/:id' => 'home#individual_athlete', as: 'individual_athlete'
  post 'home/profile_update', to: 'home#profile_field_update'
  post '/home/athletes_list', to: 'home#athletes_list', as: 'athletes_list'

get 'albums/album_new', to:'albums#album_new' ,as:'albums_new'
post 'albums/album_create',to:'albums#album_create',as:'albums/album_create'
get 'albums/picture_new',to:'albums#picture_new',as:'picture_new'
post'albums/picture_create',to:'albums#picture_create',as:'albums/picture_create'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
	def plans_desc
		if self.id == 1
			["1.Stand out and get in touch with hiring managers", "1.See how you compare to other applicants", "1.Learn new skills to advance your career"]
		elsif
			id == 2
			["2.Stand out and get in touch with hiring managers", "2.See how you compare to other applicants", "2.Learn new skills to advance your career"]
		elsif
			id == 3
			["3.Stand out and get in touch with hiring managers", "3.See how you compare to other applicants", "3.Learn new skills to advance your career"]
		else
			id == 4
			["4.Stand out and get in touch with hiring managers", "4.See how you compare to other applicants", "4.Learn new skills to advance your career"]
		end
	end
end

app/controllers/admin/basic/account_types_controller.rb
class Admin::Basic::AccountTypesController < ApplicationController
  def index
  end
end

app/controllers/admin/basic/cities_controller.rb
class Admin::Basic::CitiesController < ApplicationController
  def index
  end
end

app/controllers/admin/basic/countries_controller.rb
class Admin::Basic::CountriesController < ApplicationController
  def index
  end
end

app/controllers/admin/basic/games_controller.rb
class Admin::Basic::GamesController < ApplicationController
  def index
  end
end

app/controllers/admin/basic/plans_controller.rb
class Admin::Basic::PlansController < ApplicationController
	def index
		@plans = Plan.all
	end

	def new
		@plan = Plan.new
	end

	def create
		Plan.create(plan_params)
		redirect_to admin_basic_plans_path
	end

	def edit
		@plan = Plan.find(params[:id])
	end

	def update
		@plan = Plan.find(params[:id])
		if @plan.update(plan_params)
			redirect_to admin_basic_plans_path
		else
			render 'edit'
		end

	end

	def destroy
		@plan = Plan.find(params[:id])
		@plan.destroy
		redirect_to admin_basic_plans_path
	end

	private

	def plan_params
		params.require(:plan).permit(:name, :description, :price)
	end

end

app/controllers/admin/basic/states_controller.rb
class Admin::Basic::StatesController < ApplicationController
  def index
  end
end

app/helpers/admin/pages/plans_helper.rb
module Admin::Pages::PlansHelper
end

app/views/admin/basic/plans/edit.html.erb
<h1>Editing plan</h1>
 
<%= form_for :plan, url: admin_basic_plan_path(id: @plan.id), method: :patch do |f| %>
 
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@plan.errors.count, "error") %> prohibited
        this plan from being saved:
      </h2>
      <ul>
        <% @plan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :Price %><br>
    <%= f.text_area :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', admin_basic_plans_path %>

app/views/admin/basic/plans/index.html.erb
<%= link_to "New Plan", new_admin_basic_plan_path, class:"btn btn-default" %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Action</th>
    <th colspan="2"></th>
  </tr>
 
  <% @plans.each do |plan| %>
    <tr>
      <td><%= plan.name %></td>
      <td><%= plan.description %></td>
      <td><%= plan.price %></td>
      <td><%= link_to 'Edit', edit_admin_basic_plan_path(plan), class:"btn btn-default" %></td>
      <td><%= link_to 'Destroy', admin_basic_plan_path(plan), class:"btn btn-default",  method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Home", admin_path %>

app/views/admin/basic/plans/new.html.erb
<%= form_for :plan, url: admin_basic_plans_path do |f| %>
 
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@plan.errors.count, "error") %> prohibited
        this plan from being saved:
      </h2>
      <ul>
        <% @plan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :Price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', admin_basic_plans_path %>