config/routes.rb
Rails.application.routes.draw do
  match 'auth/facebook/callback', to: 'home#facebook_details', via: [:get, :post]
  match 'auth/instagram/callback', to: 'home#instagram_details', via: [:get, :post]
  match 'auth/pinterest/callback', to: 'home#pinterest_details', via: [:get, :post]
  match 'auth/google/callback', to: 'home#google_details', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match '*path', via: [:options], to:  ->(_) { [200, { 'Content-Type' => 'text/plain' }, []] }

  devise_scope :user do
    post 'users/sessions/login', to: 'users/sessions#login', as: 'user_login'
  end  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  post '/users/confirm_registration' => 'users#confirm_registration'
  get 'get_countries' => 'homes#get_countries'
  get 'get_roles' => 'homes#get_roles'
  get '/users/sessions/failure' => 'users/sessions#failure'
  delete 'sessions' => 'sessions#destroy', :as => 'sign_out'

  get '/user_video/add_video', to: 'user_videos#add_video', as: 'add_video'
  post '/user_video/upload_video', to: 'user_videos#upload_video', as: 'upload_video'
  delete '/user_video/remove_video/:id', to: 'user_videos#remove_video', as: 'remove_video'
  post '/user_video/add_videos', to: 'user_videos#add_videos', as: 'add_videos'
  
  patch '/athletes', to: 'athletes#profile_field_update'
  post '/athletes/public_image', to: 'athletes#update_public_image'
  post '/athletes/cover_image', to: 'athletes#update_cover_image'
  get '/athletes/profile', to: 'athletes#profile'
  get '/athletes/skills', to: 'athletes#skills'
  post '/athletes/skills', to: 'skills#add'
  delete '/athletes/skills', to: 'skills#remove'
  post '/athletes/educations', to: 'educations#create'
  delete '/athletes/educations', to: 'educations#delete'
  put'/athletes/educations', to: 'educations#edit'

  get '/skills', to: 'skills#index'
  get '/skills', to: 'skills#index'
  get '/educations', to: 'educations#index'
  get '/institution', to: 'educations#institution'
  get '/education_type', to: 'educations#education_type'
  post '/charges/creditcard_payment', to: 'charges#creditcard_payment'
  post '/charges/user_stripe_account_id', to: 'charges#user_stripe_account_id'

  get '/payments/upgrade_plans', to: 'payments#upgrade_plans', as: 'upgrade_plans'
  get '/payments/payment_option_page/:id', to: 'payments#payment_option_page', as: 'payment_option_page'
  post '/payments/creditcard_validation',to:'payments#creditcard_validation'
  post '/payments/payment_charge',to:'payments#payment_charge'
  post '/charges/paypal_payment', to: 'charges#paypal_payment'
  post '/payments/stripe_payment', to: 'payments#stripe_payment', as: 'stripe_payment'

  get 'careers/add_career',to: 'careers#add_career' 
  post 'careers/add_career_create',to:'careers#add_career_create',as:'add_careers_create'
  get 'careers/career_edit/:career_id',to: 'careers#career_edit' ,as:'career_edit'
  put 'careers/career_update/:career_id',to: 'careers#career_update',as:'career_update'
  delete 'careers/:career_id', to: 'careers#career_destroy', as: 'career_destroy'

  get 'sponsors/sponsor_new',to: 'sponsors#sponsor_new',as:'sponsors_new'
  post 'sponsors/sponsor_create',to:'sponsors#sponsor_create',as:'sponsor_create'
  get 'sponsors/sponsor_edit/:sponsor_id',to:'sponsors#sponsor_edit',as:'sponsor_edit'
  put 'sponsors/sponsor_update/:sponsor_id',to: 'sponsors#sponsor_update',as:'sponsor_update'
  delete 'sponsors/sponsor_destroy/:sponsor_id',to:'sponsors#sponsor_destroy',as:'sponsor_destroy'

  namespace :admin do
    devise_for :users
    get '/', to: 'dashboard#index'
    resources :users

    namespace :basic do
      resources :countries do
      end
      resources :states do
      end
      resources :cities do
      end
      resources :account_types do
      end
      resources :plans do
      end
      resources :games do
      end
    end
  end
      

  root 'home#index'

  get 'home/index'
  get 'home/view'
  get 'home/edit_profile'
  post 'home/create'
  post 'home/add_education'
  post 'home/add_experiences'
  
  delete 'home/edit_profile', to: 'home#destroy'
  
  patch '/home', to: 'home#update_user_profile'
  put '/home', to: 'home#update_user_profile'
  get '/home/athletes_list'
  get '/home/athlete_campare'
  get '/home/athlete_campare_page'
  get '/home/individual_athlete/:id' => 'home#individual_athlete', as: 'individual_athlete'
  post 'home/profile_update', to: 'home#profile_field_update'
  post '/home/athletes_list', to: 'home#athletes_list', as: 'athletes_list'

get 'albums/album_new', to:'albums#album_new' ,as:'albums_new'
post 'albums/album_create',to:'albums#album_create',as:'albums/album_create'
get 'albums/picture_new',to:'albums#picture_new',as:'picture_new'
post'albums/picture_create',to:'albums#picture_create',as:'albums/picture_create'

end

app/controllers/api/v1/payments_controller.rb
class PaymentsController < ApplicationController
	require "active_merchant/billing/model"
	def creditcard_validation
		cc = ActiveMerchant::Billing::CreditCard.new(
			:type               => params[:type],
			:number             => params[:number],
			:verification_value => params[:verification_value],
			:month              => params[:month],
			:year               => params[:year],
			:first_name         => params[:first_name],
			:last_name          => params[:last_name]
			)
		validation = cc.validate
		if validation.blank?
			render_success(msg: 'Credit Card Validation Success')
		else
			render_failed(errors: errors_full_msg(validation))
		end
	end

	def  payment_charge
		
		ActiveMerchant::Billing::Base.mode = :test
		gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
			:login => 'seller201@yopmail.com',
			:password => 'seller201@yopmail')
		cc = ActiveMerchant::Billing::CreditCard.new(
			:type               => params[:type],
			:number             => params[:number],
			:verification_value => params[:verification_value],
			:month              => params[:month],
			:year               => params[:year],
			:first_name         => params[:first_name],
			:last_name          => params[:last_name]

			)
		amount = params[:amount].to_i

		p "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@2222"
		p validation = cc.validate
		if validation.blank?
			p 'asddgsdg'
			# p response = gateway.authorize((amount * 100), cc, purchase_options)
			if response.success?
				p "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@2"
				p transaction = gateway.capture(amount *100,response.authorization)

				p "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
				if p transaction.success?
					p "#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
					# cc = PaymentHistory.create(status:params[:status],user_id: params[:user_id])
					# cc.save

					render_success(msg:"The transaction has been successfully charged.")
				else
					render_failed(msg: 'The credit card you provided was declined.  Please double check your information and try again.')
				end
				#update_attribute({authorization_code: transaction.authorization, success: true})
			else
				render_failed(errors: response.message)
				# errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.")
			end	
		else
			render_failed(msg: errors_full_msg(validation))
		end
	end		
  # create_table "payment_histories", force: :cascade do |t|
  #   t.integer  "user_id",      limit: 4
  #   t.string   "payment_type", limit: 255
  #   t.string   "amount",       limit: 255
  #   t.string   "status",       limit: 255

  private

  def errors_full_msg(h)
  	h.collect {|k, v| k.to_s.humanize + ' ' +  v.first }
  end

  def purchase_options
  	{
  		:ip => request.remote_ip,
			# :billing_address => {
			# 	:name     => "Ryan Bates",
			# 	:address1 => "123 Main St.",
			# 	:city     => "New York",
			# 	:state    => "NY",
			# 	:country  => "US",
			# 	:zip      => "10001"
			# }
		}
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	include JsonRenderHelper
	require "active_merchant/billing/model"
	def upgrade_plans
		@plans = Plan.all
	end

	def payment_option_page
		@plan = Plan.find(params[:id])
	end

	def stripe_payment
		require 'payments'
		amount = params[:price]
		payments_obj = Payments.new
		if current_user.stripe_account_id.blank?
			stripe_account_id = payments_obj.create_customer(current_user, params[:stripeToken])
			current_user.update(stripe_account_id: stripe_account_id)
		end
		if payments_obj.charge(current_user, amount, params[:stripeToken])
			current_user.payment_histories.create(payment_type: "stripe", amount: amount, status: "success")
			exp_date = current_user.payment_plan( params[:plan_id])
			if current_user.user_plan.present?
				current_user.user_plan.update(expiry_date: exp_date)
			else
				@user_payment = current_user.create_user_plan(plan_id: params[:plan_id], amount: amount, payment_type: "Stripe", status: "Active", expiry_date: exp_date )
			end
			render_success msg: "Payment success.! Now, you are a premium member"
		else 
			payments_obj.error_message
			current_user.payment_histories.create(payment_type: "stripe", amount: amount, status: "failed")
		  render_failed msg: 'Payment false. Cannot create your plan'
		end
	end

	def  payment_charge
		cc = ActiveMerchant::Billing::CreditCard.new(
			:type               => params[:type],
			:number             => params[:number],
			:verification_value => params[:verification_value],
			:month              => params[:month],
			:year               => params[:year],
			:first_name			=> current_user.first_name ? current_user.first_name : "",
			:last_name			=> current_user.last_name ? current_user.last_name : ""
			)
		amount = params[:price].to_i
		validation = cc.validate
		if validation.blank?
			response = GATEWAY.authorize(amount * 100, cc,purchase_options)
			if response.success?
				transaction = GATEWAY.capture(amount *100,response.authorization)
				if transaction.success?
					exp_date = current_user.payment_plan( params[:plan_id])
					if current_user.user_plan.present?
						current_user.user_plan.update(expiry_date: exp_date)
					else
						@user_payment = current_user.create_user_plan(plan_id: params[:plan_id], amount: amount, payment_type: "CreditCard", status: "Active", expiry_date: exp_date )
					end
					render :json => { :success => true , :msg => "The transaction has been successfully charged. Now you are a premium member" }
				else
					render :json => {:success => true, :errors => validation}
				end
			else
				render :json => {:success => false, :errors => validation}
			end
		else
			render :json => {:success => false, :errors => validation}
		end
	end		
	private

	def errors_full_msg(h)
		h.collect {|k, v| k.to_s.humanize + ' ' +  v.first }
	end

	def purchase_options
		{
			:ip => request.remote_ip,
		}
	end
end

app/views/payments/payment_option_page.html.erb
<div class="container">
	<div class="row">
		<h1 align="center">You can pay one of these payment options.</h1>
		<div class="col-xs-12 col-md-4" style="margin-top:5%;">
			<div class="">
				<img src="/assets/paypal.jpg" style="width:100%;height:90px;">
				<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top" style="text-align:center;margin-top:10px;">
					<input type="hidden" name="cmd" value="_xclick">
					<input type="hidden" name="business" value="seller201@yopmail.com">
					<input type="hidden" name="lc" value="IN">
					<input type="hidden" name="amount" value="<%= @plan.price%>">
					<input type="hidden" name="currency_code" value="USD">
					<input type="hidden" name="button_subtype" value="services">
					<input type="hidden" name="no_note" value="0">
					<input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynowCC_LG.gif:NonHostedGuest">
					<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
					<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
				</form>
			</div>
		</div>  
		<!-- creditcard -->
		<div class="col-xs-12 col-md-4" style="margin-top:5%;">
			<%= form_tag stripe_payment_path, id: "stripeForm" do %>
			<plan>
				<label class="amount">
					<span>Amount: <%= @plan.price %></span>
				</label>
				<%= hidden_field_tag "price", @plan.price %>
				<%= hidden_field_tag "plan_id", @plan.id %>
				<%= hidden_field_tag "stripe_publishable_key", Rails.application.secrets.stripe_publishable_key, class:"stripe_public_key" %>
			</plan><br />
			<button id="customStripePayment" type="button" class="btn btn-primary" data-price="<%= @plan.price %>" data-name="<%= @plan.name %>" data-description="<%= @plan.description %>">Pay with card</button>
			<% end %>
		</div>
		<!-- stripe -->
		<div class="col-xs-12 col-md-4" style="margin-top:9%;">
			<!-- creditcard -->
			<img src="/assets/cards.png" style="width:100%;height:90px;">
			<div class="panel panel-default">
				<%=form_tag payments_payment_charge_path, id:"creditcard_form" do  %>
				<% if flash[:notice] %>
				<div class="notice"><%= flash[:notice] %></div>
				<% end %>
				<div class="panel-heading">
					<h3 class="panel-title"><img class="pull-right payment-image" src="/assets/payment.png">Payment Details</h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-xs-12">
							<div class="form-group">
								<label>CARD TYPE</label>
								<%= select_tag 'type', options_for_select([["Visa", "visa"], ["MasterCard", "master"],["American Express", "american_express"]]), prompt: "Select Card Type", class: "form-control" %>
								
								<label>CARD NUMBER</label>
								<div class="form-group">
									<%= text_field_tag :number,nil, placeholder: "Card Number", class: "form-control"%>
								</div>
							</div>                            
						</div>
					</div>
					<div class="row">
						<div class="col-xs-7 col-md-7">
							<div class="form-group">
								<label for="expMonth">EXPIRATION DATE</label>
								<div class="col-xs-6 col-lg-6 pl-ziro">
									<%= text_field_tag :month,nil, placeholder: "MM", class: "form-control"%>
								</div>
								<div class="col-xs-6 col-lg-6 pl-ziro">
									<%= text_field_tag :year,nil, placeholder: "YYYY", class: "form-control" ,style: "padding:8px;"%>
								</div>
							</div>
						</div>
						<div class="col-xs-5 col-md-5 pull-right">
							<div class="form-group">
								<label for="cvCode">CV CODE</label>
								<%=text_field_tag :verification_value,nil, placeholder: "CCV", class: "form-control" ,style:"padding:8px;"%>
							</div>
						</div>
					</div>
					<%=hidden_field_tag "price", @plan.price %>
					<%=hidden_field_tag "plan_id", @plan.id %>
					<div class="row">
						<div class="col-xs-12 ">
							<button class="submit_btn btn btn-primary" type="submit" id="creditcardPayment" style="float:left;">Submit</button>
							<img src="/assets/ajax-loader.gif" class="gif-loader-img">

							<!-- button type="button" class="subscribe btn btn-success btn-lg btn-block" value="submit">Start Subscription</button> -->
						</div>
					</div>
					<div class="row" style="display:none;">
						<div class="col-xs-12">
							<p class="payment-errors"></p>
						</div>
					</div>
				</div>
				<%end%>
			</div>
		</div>     
	</div>
</div>